# Product Line Profitability & Margin Performance Analysis

# Notebook 2 : Data Cleaning & Validation

## Objective

The objective of this notebook is to clean and validate the raw dataset before analysis.

This notebook will cover:

- Load raw dataset
- Create backup
- Data quality checks
- Handle missing values
- Remove duplicates
- Validate numerical columns
- Standardize text columns
- Convert date columns
- Save cleaned dataset

**Industry Standard Workflow**

Raw Dataset
↓
Data Cleaning
↓
Data Validation
↓
Clean Dataset
↓
EDA

In [ ]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings("ignore")

print("✅ Libraries Imported Successfully")

✅ Libraries Imported Successfully

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

print(os.listdir("/content/drive"))

['.shortcut-targets-by-id', 'MyDrive', '.Trash-0', '.Encrypted']

In [ ]:
print(os.listdir("/content/drive/MyDrive"))

['Colab Notebooks', ' Kanishka Sharma.pdf', 'Cu', '25BDA70175_Kanishka Sharma.pdf', '25BDA70175_Kaniska Sharma.pdf .pdf', '25BDA70175_KANISHKA SHARMA (1).pdf', '25BDA70175_KANISHKA SHARMA.pdf', 'Presentation ', 'Nassau_Candy_Project']

In [ ]:
import pandas as pd
import os

raw_path = "/content/drive/MyDrive/Nassau_Candy_Project/data/raw"

print("Files:", os.listdir(raw_path))

filename = os.listdir(raw_path)[0]

dataset_path = os.path.join(raw_path, filename)

df = pd.read_csv(dataset_path)

print("✅ Dataset Loaded Successfully")

df.head()

Files: ['Nassau Candy Distributor.csv', 'raw_backup.csv']
✅ Dataset Loaded Successfully

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
# 1. Import Libraries
import pandas as pd
import numpy as np
import os

# 2. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 3. Load Dataset
df = pd.read_csv("/content/drive/MyDrive/Nassau_Candy_Project/data/raw/Nassau Candy Distributor.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost']

In [ ]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("/", "_")
)

print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country_region', 'city', 'state_province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost'],
      dtype='object')

In [ ]:
for col in df.columns:
    print(col)

row_id
order_id
order_date
ship_date
ship_mode
customer_id
country_region
city
state_province
postal_code
division
region
product_id
product_name
sales
units
gross_profit
cost

In [ ]:
# ==========================================
#  Convert Date Columns
# ==========================================

date_columns = ["order_date", "ship_date"]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print("✅ Date Columns Converted Successfully")

df[date_columns].head()

✅ Date Columns Converted Successfully

  order_date  ship_date
0 2024-03-01 2026-06-30
1 2024-04-01 2026-07-01
2 2024-04-01 2026-07-01
3 2024-04-01 2026-07-01
4 2024-05-01 2026-07-05

In [ ]:
# ==========================================
# Missing Values Report
# ==========================================

missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum().values,
    "Percentage": (
        df.isnull().sum().values / len(df) * 100
    ).round(2)
})

missing_report

            Column  Missing Values  Percentage
0           row_id               0        0.00
1         order_id               0        0.00
2       order_date            6064       59.49
3        ship_date               0        0.00
4        ship_mode               0        0.00
5      customer_id               0        0.00
6   country_region               0        0.00
7             city               0        0.00
8   state_province               0        0.00
9      postal_code               0        0.00
10        division               0        0.00
11          region               0        0.00
12      product_id               0        0.00
13    product_name               0        0.00
14           sales               0        0.00
15           units               0        0.00
16    gross_profit               0        0.00
17            cost               0        0.00

In [ ]:
negative_sales = df[df["sales"] < 0]

print("Negative Sales Records :", len(negative_sales))

Negative Sales Records : 0

In [ ]:
negative_cost = df[df["cost"] < 0]

print("Negative Cost Records :", len(negative_cost))

Negative Cost Records : 0

In [ ]:
negative_profit = df[df["gross_profit"] < 0]

print("Negative Profit Records :", len(negative_profit))

Negative Profit Records : 0

In [ ]:
zero_sales = df[df["sales"] == 0]

print("Zero Sales Records :", len(zero_sales))

Zero Sales Records : 0

In [ ]:
zero_units = df[df["units"] == 0]

print("Zero Units :", len(zero_units))

Zero Units : 0

In [ ]:
df["calculated_profit"] = df["sales"] - df["cost"]

df["difference"] = (
    df["gross_profit"] -
    df["calculated_profit"]
).round(2)

df[[
    "sales",
    "cost",
    "gross_profit",
    "calculated_profit",
    "difference"
]].head()

   sales  cost  gross_profit  calculated_profit  difference
0   6.50  2.28          4.22               4.22       -0.00
1   7.50  2.60          4.90               4.90        0.00
2  10.47  3.00          7.47               7.47       -0.00
3  10.80  3.30          7.50               7.50       -0.00
4  11.25  3.90          7.35               7.35        0.00

In [ ]:
wrong_profit = df[df["difference"] != 0]

print("Incorrect Profit Records :", len(wrong_profit))

Incorrect Profit Records : 0

In [ ]:
print("="*60)

print("DATA VALIDATION SUMMARY")

print("="*60)

print("Rows :", len(df))

print("Columns :", len(df.columns))

print("Missing Values :", df.isnull().sum().sum())

print("Duplicate Rows :", df.duplicated().sum())

print("Negative Sales :", len(negative_sales))

print("Negative Cost :", len(negative_cost))

print("Negative Profit :", len(negative_profit))

print("Zero Sales :", len(zero_sales))

print("Zero Units :", len(zero_units))

print("="*60)

============================================================
DATA VALIDATION SUMMARY
============================================================
Rows : 10194
Columns : 20
Missing Values : 6064
Duplicate Rows : 0
Negative Sales : 0
Negative Cost : 0
Negative Profit : 0
Zero Sales : 0
Zero Units : 0
============================================================

In [ ]:
validation_report = pd.DataFrame({
    "Metric":[
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows",
        "Negative Sales",
        "Negative Cost",
        "Negative Profit",
        "Zero Sales",
        "Zero Units"
    ],
    "Value":[
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(negative_sales),
        len(negative_cost),
        len(negative_profit),
        len(zero_sales),
        len(zero_units)
    ]
})

validation_report.to_csv(
"/content/drive/MyDrive/Nassau_Candy_Project/reports/Data_Validation_Report.csv",
index=False
)

print("✅ Validation Report Saved")

✅ Validation Report Saved